name: sgm
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.1
  row_row_row: ^0.1.3
  supabase_flutter: ^2.3.1
  flutter_quill: ^11.4.1
  flutter_expandable_fab: ^2.5.1
  flutter_easyloading: ^3.0.5
  country_picker: ^2.0.27
  infinite_calendar_view: ^2.5.4
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets
  assets:
    - assets/
    # You can also specify subdirectories for better organization:
    - assets/images/
    # - assets/icons/
    # - assets/fonts/
    
  # Add custom fonts
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: google_fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: google_fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: google_fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: google_fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: google_fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: google_fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: google_fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/NotoSansKR-Black.ttf
          weight: 900
          
    # PlayfairDisplay font family
    - family: PlayfairDisplay
      fonts:
        - asset: google_fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: google_fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: google_fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: google_fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: google_fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: google_fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: google_fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: google_fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: google_fonts/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: google_fonts/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic


