name: sgm
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  row_row_row: ^0.1.3
  supabase_flutter: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets
  assets:
    - assets/
    # You can also specify subdirectories for better organization:
    - assets/images/
    # - assets/icons/
    # - assets/fonts/
    
  # Add custom fonts
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: google_fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: google_fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: google_fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: google_fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: google_fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: google_fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: google_fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/NotoSansKR-Black.ttf
          weight: 900

