// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class AnnouncementUserRow {
  static const field = (
    id: 'id',
    announcement: 'announcement',
    user: 'user',
    createdAt: 'created_at',
  );

  final String id;
  final String? announcement;
  final String? user;
  final DateTime createdAt;

  const AnnouncementUserRow({
    required this.id,
    this.announcement,
    this.user,
    required this.createdAt,
  });

  factory AnnouncementUserRow.fromJson(Map<String, dynamic> json) {
    return AnnouncementUserRow(
      id: json[field.id] as String,
      announcement: json[field.announcement],
      user: json[field.user],
      createdAt: DateTime.parse(json[field.createdAt]),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.announcement: announcement,
      field.user: user,
      field.createdAt: createdAt.toIso8601String(),
    };
  }
}
