// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class AnnouncementTargetAudienceViewRow {
  static const field = (
    announcementId: 'announcement_id',
    announcementTitle: 'announcement_title',
    announcementContent: 'announcement_content',
    announcementCreatedAt: 'announcement_created_at',
    taggedGroupIds: 'tagged_group_ids',
    taggedGroupNames: 'tagged_group_names',
    taggedRoleIds: 'tagged_role_ids',
    taggedRoleNames: 'tagged_role_names',
    taggedUserIds: 'tagged_user_ids',
    taggedUserNames: 'tagged_user_names',
  );

  final String? announcementId;
  final String? announcementTitle;
  final String? announcementContent;
  final DateTime? announcementCreatedAt;
  final dynamic? taggedGroupIds;
  final dynamic? taggedGroupNames;
  final dynamic? taggedRoleIds;
  final dynamic? taggedRoleNames;
  final dynamic? taggedUserIds;
  final dynamic? taggedUserNames;

  const AnnouncementTargetAudienceViewRow({
    this.announcementId,
    this.announcementTitle,
    this.announcementContent,
    this.announcementCreatedAt,
    this.taggedGroupIds,
    this.taggedGroupNames,
    this.taggedRoleIds,
    this.taggedRoleNames,
    this.taggedUserIds,
    this.taggedUserNames,
  });

  factory AnnouncementTargetAudienceViewRow.fromJson(
    Map<String, dynamic> json,
  ) {
    return AnnouncementTargetAudienceViewRow(
      announcementId: json[field.announcementId],
      announcementTitle: json[field.announcementTitle],
      announcementContent: json[field.announcementContent],
      announcementCreatedAt:
          json[field.announcementCreatedAt] == null
              ? null
              : DateTime.tryParse(json[field.announcementCreatedAt] ?? ''),
      taggedGroupIds: json[field.taggedGroupIds],
      taggedGroupNames: json[field.taggedGroupNames],
      taggedRoleIds: json[field.taggedRoleIds],
      taggedRoleNames: json[field.taggedRoleNames],
      taggedUserIds: json[field.taggedUserIds],
      taggedUserNames: json[field.taggedUserNames],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.announcementId: announcementId,
      field.announcementTitle: announcementTitle,
      field.announcementContent: announcementContent,
      field.announcementCreatedAt: announcementCreatedAt?.toIso8601String(),
      field.taggedGroupIds: taggedGroupIds,
      field.taggedGroupNames: taggedGroupNames,
      field.taggedRoleIds: taggedRoleIds,
      field.taggedRoleNames: taggedRoleNames,
      field.taggedUserIds: taggedUserIds,
      field.taggedUserNames: taggedUserNames,
    };
  }
}
