// Generated by row_row_row tool
// Auto-generated file. Do not modify.
import 'dart:convert';

class AnnouncementRow {
  static const field = (
    id: 'id',
    title: 'title',
    content: 'content',
    createdBy: 'created_by',
    createdAt: 'created_at',
    deletedAt: 'deleted_at',
    personal: 'personal',
    routeData: 'route_data',
  );

  final String id;
  final String? title;
  final String? content;
  final String? createdBy;
  final DateTime createdAt;
  final DateTime? deletedAt;
  final bool personal;
  final Map<String, dynamic>? routeData;

  const AnnouncementRow({
    required this.id,
    this.title,
    this.content,
    this.createdBy,
    required this.createdAt,
    this.deletedAt,
    required this.personal,
    this.routeData,
  });

  factory AnnouncementRow.fromJson(Map<String, dynamic> json) {
    return AnnouncementRow(
      id: json[field.id] as String,
      title: json[field.title],
      content: json[field.content],
      createdBy: json[field.createdBy],
      createdAt: DateTime.parse(json[field.createdAt]),
      deletedAt: json[field.deletedAt] == null ? null : DateTime.tryParse(json[field.deletedAt] ?? ''),
      personal: json[field.personal] as bool,
      routeData: json[field.routeData] == null ? null : (json[field.routeData] is String ? jsonDecode(json[field.routeData]) : Map<String, dynamic>.from(json[field.routeData])),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.title: title,
      field.content: content,
      field.createdBy: createdBy,
      field.createdAt: createdAt.toIso8601String(),
      field.deletedAt: deletedAt?.toIso8601String(),
      field.personal: personal,
      field.routeData: routeData,
    };
  }
}
