// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ChatLastSeenRow {
  static const field = (
    chatId: 'chat_id',
    userId: 'user_id',
    lastSeenAt: 'last_seen_at',
  );

  final String chatId;
  final String userId;
  final DateTime lastSeenAt;

  const ChatLastSeenRow({
    required this.chatId,
    required this.userId,
    required this.lastSeenAt,
  });

  factory ChatLastSeenRow.fromJson(Map<String, dynamic> json) {
    return ChatLastSeenRow(
      chatId: json[field.chatId] as String,
      userId: json[field.userId] as String,
      lastSeenAt: DateTime.parse(json[field.lastSeenAt]),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.chatId: chatId,
      field.userId: userId,
      field.lastSeenAt: lastSeenAt.toIso8601String(),
    };
  }
}
