// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ClinicAreaProcedureCategoryDropdownEntriesRow {
  static const field = (
    clinicAreaId: 'clinic_area_id',
    areaName: 'area_name',
    clinicId: 'clinic_id',
    clinicName: 'clinic_name',
    procedureCategoryId: 'procedure_category_id',
    procedureCategoryName: 'procedure_category_name',
  );

  final String? clinicAreaId;
  final String? areaName;
  final String? clinicId;
  final String? clinicName;
  final String? procedureCategoryId;
  final String? procedureCategoryName;

  const ClinicAreaProcedureCategoryDropdownEntriesRow({
    this.clinicAreaId,
    this.areaName,
    this.clinicId,
    this.clinicName,
    this.procedureCategoryId,
    this.procedureCategoryName,
  });

  factory ClinicAreaProcedureCategoryDropdownEntriesRow.fromJson(Map<String, dynamic> json) {
    return ClinicAreaProcedureCategoryDropdownEntriesRow(
      clinicAreaId: json[field.clinicAreaId],
      areaName: json[field.areaName],
      clinicId: json[field.clinicId],
      clinicName: json[field.clinicName],
      procedureCategoryId: json[field.procedureCategoryId],
      procedureCategoryName: json[field.procedureCategoryName],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.clinicAreaId: clinicAreaId,
      field.areaName: areaName,
      field.clinicId: clinicId,
      field.clinicName: clinicName,
      field.procedureCategoryId: procedureCategoryId,
      field.procedureCategoryName: procedureCategoryName,
    };
  }
}
