// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class CountryRow {
  static const field = (
    iso: 'iso',
    name: 'name',
    nicename: 'nicename',
    iso3: 'iso3',
    numcode: 'numcode',
    phonecode: 'phonecode',
  );

  final dynamic iso;
  final dynamic name;
  final dynamic nicename;
  final dynamic? iso3;
  final dynamic? numcode;
  final int phonecode;

  const CountryRow({
    required this.iso,
    required this.name,
    required this.nicename,
    this.iso3,
    this.numcode,
    required this.phonecode,
  });

  factory CountryRow.fromJson(Map<String, dynamic> json) {
    return CountryRow(
      iso: json[field.iso],
      name: json[field.name],
      nicename: json[field.nicename],
      iso3: json[field.iso3],
      numcode: json[field.numcode],
      phonecode: (json[field.phonecode] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.iso: iso,
      field.name: name,
      field.nicename: nicename,
      field.iso3: iso3,
      field.numcode: numcode,
      field.phonecode: phonecode,
    };
  }
}
