// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class CustomerProcedureSubtotalViewRow {
  static const field = (
    taskId: 'task_id',
    subtotal: 'subtotal',
  );

  final String? taskId;
  final double? subtotal;

  const CustomerProcedureSubtotalViewRow({
    this.taskId,
    this.subtotal,
  });

  factory CustomerProcedureSubtotalViewRow.fromJson(Map<String, dynamic> json) {
    return CustomerProcedureSubtotalViewRow(
      taskId: json[field.taskId],
      subtotal: json[field.subtotal] == null ? null : (json[field.subtotal] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.taskId: taskId,
      field.subtotal: subtotal,
    };
  }
}
