// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class FormQuestionRow {
  static const field = (
    id: 'id',
    question: 'question',
    description: 'description',
    images: 'images',
    type: 'type',
    isRequired: 'is_required',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    form: 'form',
    order: 'order',
    checkboxOptions: 'checkbox_options',
    checkboxDefault: 'checkbox_default',
    deletedAt: 'deleted_at',
  );

  final String id;
  final String? question;
  final String? description;
  final dynamic images;
  final String? type;
  final bool? isRequired;
  final DateTime createdAt;
  final DateTime? updatedAt;
  final String? form;
  final int? order;
  final dynamic checkboxOptions;
  final dynamic checkboxDefault;
  final DateTime? deletedAt;

  const FormQuestionRow({
    required this.id,
    this.question,
    this.description,
    this.images,
    this.type,
    this.isRequired,
    required this.createdAt,
    this.updatedAt,
    this.form,
    this.order,
    this.checkboxOptions,
    this.checkboxDefault,
    this.deletedAt,
  });

  factory FormQuestionRow.fromJson(Map<String, dynamic> json) {
    return FormQuestionRow(
      id: json[field.id] as String,
      question: json[field.question],
      description: json[field.description],
      images: json[field.images],
      type: json[field.type],
      isRequired: json[field.isRequired],
      createdAt: DateTime.parse(json[field.createdAt]),
      updatedAt: json[field.updatedAt] == null ? null : DateTime.tryParse(json[field.updatedAt] ?? ''),
      form: json[field.form],
      order: json[field.order] == null ? null : (json[field.order] as num?)?.toInt(),
      checkboxOptions: json[field.checkboxOptions],
      checkboxDefault: json[field.checkboxDefault],
      deletedAt: json[field.deletedAt] == null ? null : DateTime.tryParse(json[field.deletedAt] ?? ''),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.question: question,
      field.description: description,
      field.images: images,
      field.type: type,
      field.isRequired: isRequired,
      field.createdAt: createdAt.toIso8601String(),
      field.updatedAt: updatedAt?.toIso8601String(),
      field.form: form,
      field.order: order,
      field.checkboxOptions: checkboxOptions,
      field.checkboxDefault: checkboxDefault,
      field.deletedAt: deletedAt?.toIso8601String(),
    };
  }
}
