// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class NextOrderOfStatusRow {
  static const field = (
    project: 'project',
    nextOrder: 'next_order',
  );

  final String? project;
  final int? nextOrder;

  const NextOrderOfStatusRow({
    this.project,
    this.nextOrder,
  });

  factory NextOrderOfStatusRow.fromJson(Map<String, dynamic> json) {
    return NextOrderOfStatusRow(
      project: json[field.project],
      nextOrder: json[field.nextOrder] == null ? null : (json[field.nextOrder] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.project: project,
      field.nextOrder: nextOrder,
    };
  }
}
