// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class NumberOfTasksPerProjectRow {
  static const field = (
    projectId: 'project_id',
    totalTasks: 'total_tasks',
  );

  final String? projectId;
  final int? totalTasks;

  const NumberOfTasksPerProjectRow({
    this.projectId,
    this.totalTasks,
  });

  factory NumberOfTasksPerProjectRow.fromJson(Map<String, dynamic> json) {
    return NumberOfTasksPerProjectRow(
      projectId: json[field.projectId],
      totalTasks: json[field.totalTasks] == null ? null : (json[field.totalTasks] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.projectId: projectId,
      field.totalTasks: totalTasks,
    };
  }
}
