// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class NumberOfTasksPerProjectStatusRow {
  static const field = (
    project: 'project',
    status: 'status',
    numberOfTasks: 'number_of_tasks',
  );

  final String? project;
  final String? status;
  final int? numberOfTasks;

  const NumberOfTasksPerProjectStatusRow({
    this.project,
    this.status,
    this.numberOfTasks,
  });

  factory NumberOfTasksPerProjectStatusRow.fromJson(Map<String, dynamic> json) {
    return NumberOfTasksPerProjectStatusRow(
      project: json[field.project],
      status: json[field.status],
      numberOfTasks: json[field.numberOfTasks] == null ? null : (json[field.numberOfTasks] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.project: project,
      field.status: status,
      field.numberOfTasks: numberOfTasks,
    };
  }
}
