// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class SubtaskAssigneeRow {
  static const field = (
    id: 'id',
    createdAt: 'created_at',
    assignee: 'assignee',
    assignedBy: 'assigned_by',
    subtask: 'subtask',
  );

  final String id;
  final DateTime createdAt;
  final String? assignee;
  final String? assignedBy;
  final String? subtask;

  const SubtaskAssigneeRow({
    required this.id,
    required this.createdAt,
    this.assignee,
    this.assignedBy,
    this.subtask,
  });

  factory SubtaskAssigneeRow.fromJson(Map<String, dynamic> json) {
    return SubtaskAssigneeRow(
      id: json[field.id] as String,
      createdAt: DateTime.parse(json[field.createdAt]),
      assignee: json[field.assignee],
      assignedBy: json[field.assignedBy],
      subtask: json[field.subtask],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.createdAt: createdAt.toIso8601String(),
      field.assignee: assignee,
      field.assignedBy: assignedBy,
      field.subtask: subtask,
    };
  }
}
