// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskClinicRefundSumRow {
  static const field = (
    taskId: 'task_id',
    clinic: 'clinic',
    refundSum: 'refund_sum',
  );

  final String? taskId;
  final String? clinic;
  final double? refundSum;

  const TaskClinicRefundSumRow({
    this.taskId,
    this.clinic,
    this.refundSum,
  });

  factory TaskClinicRefundSumRow.fromJson(Map<String, dynamic> json) {
    return TaskClinicRefundSumRow(
      taskId: json[field.taskId],
      clinic: json[field.clinic],
      refundSum: json[field.refundSum] == null ? null : (json[field.refundSum] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.taskId: taskId,
      field.clinic: clinic,
      field.refundSum: refundSum,
    };
  }
}
