// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskAppointmentGeneralExpenseRow {
  static const field = (
    id: 'id',
    name: 'name',
    details: 'details',
    amount: 'amount',
    appointment: 'appointment',
    date: 'date',
    createdAt: 'created_at',
    createdBy: 'created_by',
  );

  final String id;
  final String? name;
  final String? details;
  final double amount;
  final String? appointment;
  final DateTime? date;
  final DateTime createdAt;
  final String? createdBy;

  const TaskAppointmentGeneralExpenseRow({
    required this.id,
    this.name,
    this.details,
    required this.amount,
    this.appointment,
    this.date,
    required this.createdAt,
    this.createdBy,
  });

  factory TaskAppointmentGeneralExpenseRow.fromJson(Map<String, dynamic> json) {
    return TaskAppointmentGeneralExpenseRow(
      id: json[field.id] as String,
      name: json[field.name],
      details: json[field.details],
      amount: (json[field.amount] as num).toDouble(),
      appointment: json[field.appointment],
      date: json[field.date] == null ? null : DateTime.tryParse(json[field.date] ?? ''),
      createdAt: DateTime.parse(json[field.createdAt]),
      createdBy: json[field.createdBy],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.name: name,
      field.details: details,
      field.amount: amount,
      field.appointment: appointment,
      field.date: date?.toIso8601String(),
      field.createdAt: createdAt.toIso8601String(),
      field.createdBy: createdBy,
    };
  }
}
