// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class UserTaskCountsRow {
  static const field = (
    userId: 'user_id',
    numberOfTasksSubtasksAppointments: 'number_of_tasks_subtasks_appointments',
  );

  final String? userId;
  final int? numberOfTasksSubtasksAppointments;

  const UserTaskCountsRow({
    this.userId,
    this.numberOfTasksSubtasksAppointments,
  });

  factory UserTaskCountsRow.fromJson(Map<String, dynamic> json) {
    return UserTaskCountsRow(
      userId: json[field.userId],
      numberOfTasksSubtasksAppointments: json[field.numberOfTasksSubtasksAppointments] == null ? null : (json[field.numberOfTasksSubtasksAppointments] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.userId: userId,
      field.numberOfTasksSubtasksAppointments: numberOfTasksSubtasksAppointments,
    };
  }
}
